version: '3.8'

networks:
  neo4j-network:
    driver: bridge

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:neo4j

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  neo4j:
    image: bitnami/neo4j:latest
    networks:
      - neo4j-network
    volumes:
    - ./neo4j-persistence:/bitnami
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
